export enum ErrorCodes {
  SYNTAX_ERROR = "SYNTAX",
  VALIDATION_ERROR = "VALIDATION",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  PASSWORD_ERROR = "PASSWORD",
  DATABASE_ERROR = "DATABASE",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
